baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "digitalreformer.com"
theme = "digital-puritan"
author = "therecluse26"
pygmentsUseClasses = true
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true

[module]
  noProxy = "none"
  private = "*.*"
  proxy = "direct"

   [[module.mounts]]
    source = "themes"
    target = "themes"